abstract final class TypeIds {
  static const moduleBundle = 'moduleBundle';
  static const app = 'app';
  static const layer = 'layer';
  static const geo = 'geo';
  static const geoSource = 'geoSource';
  static const geoRule = 'geoRule';
  static const geoStyle = 'geoStyle';
  static const info = 'info';
  static const infoSection = 'infoSection';
  static const fieldRow = 'fieldRow';
  static const imageSection = 'imageSection';
  static const attachmentSection = 'attachmentSection';
  static const inspectionTab = 'inspectionTab';
  static const inspectionObject = 'inspectionObject';
  static const inspectionCreation = 'inspectionCreation';
  static const actionInformationChange = 'actionInformationChange';
  static const actionGeometryChange = 'actionGeometryChange';
  static const actionUnknown = 'actionUnknown';
  static const objectCreation = 'objectCreation';
  static const geometryType = 'geometryType';
}
